---
- hosts: webserver
  become: yes

  tasks:
  - name: Creates directory
    file:
      path: /tmp/hello
      state: directory

  # handlers:
  #   - name: restart supervisor
  #     service: name=supervisor state=restart