---
- name: install pip
  apt: name=python-pip state=installed
  become: yes

- name: install pip virtualenv
  apt: name=python-virtualenv

- name: install flask
  pip:
    name: flask

- name: install redis
  pip:
    name: redis

# - name: Creates count-ua
#   file: path=/tmp/count-us state=directory

- name: copy file python run
  template: src=main.py dest=/opt/count-user

- name: copy template run
  template: src=index.html dest=/opt/count-user/templates

# - name: copy file python1 run
#   template: src=hello.py dest=/tmp